### ISSUE TITLE
how to export step/igs/webgl from Obj?

### ISSUE THREAD

**Issue by selvakarna** [Viktoo/Insert3D#1]
how to export step/igs/webgl from Obj?

**Comment by Viktoo** [comment]
Are you asking how to convert between different 3D file formats?

**Comment by selvakarna** [comment]
yes @Viktoo , You did not understand question ?

**Comment by Viktoo** [comment]
I wanted to make sure I was understanding your question correctly since WebGL is not a 3D file format (unless you’re referencing the [JSON exporter](https://code.google.com/archive/p/blender-webgl-exporter/)). 

Even though this is outside the scope of this library, I’d be happy to help if you provide specific information on what you’re trying to achieve. Unfortunately, there is a different conversion process for every 3D file type so there is no generalized answer.
